OBJ	=	gnmnetwork.obj gnmgdalnetwork.obj gnmgdalrule.obj gnmmanager.obj

GDAL_ROOT	=	..

!INCLUDE ..\nmake.opt

EXTRAFLAGS =	-I..\ogr -I..\ogr\ogrsf_frmts -I..\gcore -I..\gnm -I..\gnm\frmts

default:	$(OBJ) analysis_dir

analysis_dir:
	cd analysis
	$(MAKE) /f makefile.vc
	cd ..

    
clean:
	-del *.obj
